---
- name: Other essential package installation
  hosts: kdev_hosts
  tasks:
  - name: Install other essentials
    become: true
    apt:
      pkg:
        - bison
        - build-essential
        - build-essential
        - ccache
        - cscope
        - ctags
        - curl
        - distcc
        - distccmon-gnome
        - distcc-pump
        - dwarves
        - flex
        - git
        - git-email
        - grub-customizer
        - indicator-cpufreq
        - libelf-dev
        - libncurses-dev
        - libssl-dev
        - lm-sensors
        - nmap
        - python3-dev
        - tmux
        - vim
      state: present

  - name: Ensure that the ~/.ccache dir. exists.
    file:
      path: ~/.ccache/
      state: directory

  - name: Copy ccache.conf
    copy:
      src: ~/github/linux_kernel_dev_env/config/ccache.conf
      dest: ~/.ccache/ccache.conf

  - name: Copy .gitconfig
    copy:
      src: ~/github/linux_kernel_dev_env/config/git.conf
      dest: ~/.gitconfig
